# Generated by Django 4.2 on 2023-04-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("glucose", models.IntegerField()),
                ("age", models.IntegerField()),
                ("bmi", models.FloatField()),
                ("bloodPressure", models.IntegerField()),
                ("pregnancies", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("skinThickness", models.IntegerField()),
                ("insulin", models.IntegerField()),
                ("diabetesPedigreeFn", models.IntegerField()),
            ],
        ),
    ]
