# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ls30QuWlJ8SzwT8pBp5mgsf0MZorAqI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Loading Dataset"""

data = pd.read_csv(r"/content/diabetes.csv")
data.head()

"""Checking for missing data"""

sns.heatmap(data.isnull())

"""Co-relation matrix"""

correlation = data.corr()
print(correlation)

sns.heatmap(correlation)

"""Train test split"""

X = data.drop("Outcome", axis=1)
Y = data["Outcome"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
X_train

"""**Training the model**"""

model = LogisticRegression()
model.fit(X_train, Y_train)

"""**Making predictions**"""

predictions = model.predict(X_test)
print(predictions)

"""**Evaluation**"""

accuracy = accuracy_score(predictions, Y_test)
print(accuracy)